# Generated by Django 3.2.5 on 2021-08-10 02:37

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_field', models.BooleanField()),
                ('null_boolean_field', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_field', models.TimeField(auto_now=True)),
                ('date_field', models.DateField(auto_now=True)),
                ('date_time_field', models.DateTimeField(auto_now=True)),
                ('duration_field', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='files')),
                ('file_path_field', models.FilePathField(blank=True, null=True, path=pathlib.PurePosixPath('/Users/augustogoulart/Workspace/django-saturn-admin-sandbox/media/files'))),
                ('image_field', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_ip_address_field', models.GenericIPAddressField(unpack_ipv4=True)),
                ('json_field', models.JSONField()),
                ('slug_field', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='NumericField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField()),
                ('small_integer_field', models.SmallIntegerField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=4)),
                ('integer_field', models.IntegerField()),
                ('float_field', models.FloatField()),
                ('positive_big_integer_field', models.PositiveBigIntegerField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('binary_field', models.BinaryField(max_length=255)),
                ('uuid_field', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StringField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=255)),
                ('email_field', models.EmailField(max_length=255)),
                ('url_field', models.URLField(max_length=255)),
                ('text_field', models.TextField()),
            ],
        ),
    ]
