# Generated by Django 3.2.5 on 2021-08-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numericfield',
            name='uuid_field',
        ),
        migrations.AddField(
            model_name='miscellaneousfield',
            name='uuid_field',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
